---
title: "glmer_fynbos2"
author: "Christopher Shortland"
date: '2022-06-28'
output: rmarkdown::github_document
---
# Libraries
```{r}
library(tidyverse)
library(lme4)
```
#importing final dataset
```{r}
final <- read_csv('output/final_df/final_df.csv')
```
# Load fynbos stacked df
```{r}
fyn_df <- filter(final, indicator=='fynbos')
```
#number of indicator species
```{r}
fyn_df %>% filter(!Species_Code %in% c('285',"901", "870", "985", "567", "980", "289", "51")) -> fyn_df
```
# add in year variable
```{r}
fyn_df$Year <- lubridate::year(fyn_df$StartDate)
str(fyn_df)
```
# fit random intercepts model
```{r}
# fit random intercepts model
start_time <- Sys.time()
glmer_fyn <- glmer(Presence ~ scale(Year) + (1 + scale(Year)|Species_Code) + (1|Pentad), family = 'binomial', data = fyn_df)
beepr::beep()
end_time <- Sys.time()
```
# How long did this take to run?
```{r}
end_time - start_time
```
#summary
```{r}
summary(glmer_fyn)
```
##Model coefficients
```{r}
model_coefs <- coef(glmer_fyn)$Species_Code %>% 
  rename(Intercept = `(Intercept)`, Slope = `scale(Year)`) %>% 
  rownames_to_column("Species_Code")
```
# see coefficients
```{r}
model_coefs
```
#joining stuff
```{r}
fyn_df$Species_Code <- as.factor(fyn_df$Species_Code)
testjoin <- left_join(fyn_df, model_coefs, by = "Species_Code")
```
#plotting
```{r}
model_coef_plot <- ggplot(data = testjoin, 
                          mapping = aes(x = Year, 
                                        y = Presence, 
                                        colour = Species_Code)) +
  geom_abline(aes(intercept = Intercept, 
                  slope = Slope,
                  colour = Species_Code),
      size = 1) +
  scale_y_continuous(limits = c(-4, 1)) +
  theme(legend.position = "right")
```
# see the plot
```{r}
model_coef_plot
```